### ISSUE TITLE
Enabling the mdjm plugin breaks 2-level menus

### ISSUE THREAD

**Issue by nikmartin** [mdjmplugin/mobile-dj-manager#112]
I'm using a very basic web theme called 'Spacious' (http://themegrill.com/themes/spacious/) that uses a pretty generic wordpress top menu. When I enable the plugin, hovering over a menu makes it expand as normal, but then moving down to the sub-menu makes it collapse immediately. Disabling mdjm makes the menu work properly. I have isolated it down to mdjm by disabling all plugins, verifying the menu works, then enablink only mdjm and the menu quits working

**Comment by nikmartin** [comment]
I've found that this css rule:
https://github.com/mdjm/mobile-dj-manager/blob/master/templates/mdjm.css#L261

is what is breaking the menu. Removing it seem to have made the menu work again

**Comment by mikeyhoward1977** [comment]
Thanks... saved me some digging around :)

That selector is for the event buttons on the event page. Without it the display of the buttons may be out.

Rather than remove, the actual fix is

``` css
.mdjm-action-btn-container *    {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
```

I will push an update in the next day or so to include this
